export enum MessageType {
  CUSTOMER_ORDER_CONFIRM = "CUSTOMER_ORDER_CONFIRM",
  CUSTOMER_DELIVERY_COMPLETE = "CUSTOMER_DELIVERY_COMPLETE",
  CUSTOMER_ORDER_CANCEL_REFUND = "CUSTOMER_ORDER_CANCEL_REFUND",
  CUSTOMER_DELIVERY_ARRIVE_LASTMILE = "CUSTOMER_DELIVERY_ARRIVE_LASTMILE",
  CUSTOMER_DELIVERY_PICKUP_REMINDER = "CUSTOMER_DELIVERY_PICKUP_REMINDER",
  CUSTOMER_DELIVERY_PICKUP_UPDATE = "CUSTOMER_DELIVERY_PICKUP_UPDATE",
  CUSTOMER_MATCHING_REQUEST_SUBMITTED = "CUSTOMER_MATCHING_REQUEST_SUBMITTED",
  CUSTOMER_MATCHING_REQUEST_REJECTED = "CUSTOMER_MATCHING_REQUEST_REJECTED",
  CUSTOMER_MATCHING_REQUEST_EXPIRED = "CUSTOMER_MATCHING_REQUEST_EXPIRED",
  CUSTOMER_MATCHING_REQUEST_OFFERED = "CUSTOMER_MATCHING_REQUEST_OFFERED",
  MERCHANT_WAYBILL_CREATE = "MERCHANT_WAYBILL_CREATE",
  MERCHANT_WAYBILL_COMPLETE = "MERCHANT_WAYBILL_COMPLETE",
  MERCHANT_WAYBILL_CANCEL = "MERCHANT_WAYBILL_CANCEL",
  MERCHANT_MATCHING_REQUEST_NEW = "MERCHANT_MATCHING_REQUEST_NEW",
  REFUND_REQUEST_APPLIED = "REFUND_REQUEST_APPLIED",
  REFUND_REQUEST_DENIED = "REFUND_REQUEST_DENIED",
}

export enum MessageClickThroughPathType {
  CUSTOMER_DELIVERY_ORDER_DETAIL = "CUSTOMER_DELIVERY_ORDER_DETAIL",
  CUSTOMER_COMPLETED_PRODUCT_ORDER_LIST = "CUSTOMER_COMPLETED_PRODUCT_ORDER_LIST",
  CUSTOMER_MESSAGE_CENTER = "CUSTOMER_MESSAGE_CENTER",
  CUSTOMER_REQUEST_DETAIL_PAGE = "CUSTOMER_REQUEST_DETAIL_PAGE",
  CUSTOMER_RETURN_APPLICATION_DETAILS = "CUSTOMER_RETURN_APPLICATION_DETAILS",
  CUSTOMER_OFFER_PAGE = "CUSTOMER_OFFER_PAGE",
  MERCHANT_WAYBILL_DETAIL = "MERCHANT_WAYBILL_DETAIL",
  MERCHANT_REQUEST_LIST_PAGE = "MERCHANT_REQUEST_LIST_PAGE",
}

export enum MessageReceipientCategory {
  MERCHANT = "MERCHANT",
  CUSTOMER = "CUSTOMER",
}

export const MessageReceipientCategoryMap: Map<MessageType, string> = new Map([
  [MessageType.CUSTOMER_ORDER_CONFIRM, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_DELIVERY_COMPLETE, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_ORDER_CANCEL_REFUND, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_DELIVERY_ARRIVE_LASTMILE, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_DELIVERY_PICKUP_REMINDER, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_DELIVERY_PICKUP_UPDATE, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_MATCHING_REQUEST_SUBMITTED, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_MATCHING_REQUEST_REJECTED, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_MATCHING_REQUEST_EXPIRED, MessageReceipientCategory.CUSTOMER],
  [MessageType.CUSTOMER_MATCHING_REQUEST_OFFERED, MessageReceipientCategory.CUSTOMER],
  [MessageType.REFUND_REQUEST_APPLIED, MessageReceipientCategory.CUSTOMER],
  [MessageType.REFUND_REQUEST_DENIED, MessageReceipientCategory.CUSTOMER],
  [MessageType.MERCHANT_WAYBILL_CREATE, MessageReceipientCategory.MERCHANT],
  [MessageType.MERCHANT_WAYBILL_COMPLETE, MessageReceipientCategory.MERCHANT],
  [MessageType.MERCHANT_WAYBILL_CANCEL, MessageReceipientCategory.MERCHANT],
  [MessageType.MERCHANT_MATCHING_REQUEST_NEW, MessageReceipientCategory.MERCHANT],
]);

export enum EmailProvider {
  SENDGRID = "SENDGRID",
  ACTIVECAMPAIGN = "ACTIVECAMPAIGN",
}
